Update debug_traceTransaction/tracer.js
TypeError: Assignment to constant variable. at putGas
(cherry picked from commit 9d0ec00124d77f596827068a248dbdb3875b06ff)